import { FIELDS_OF_STUDY } from "@/lib/job-builder";

export const APPLICANT_COUNTRIES = [
  "Algeria",
  "Angola",
  "Argentina",
  "Australia",
  "Bangladesh",
  "Belgium",
  "Botswana",
  "Brazil",
  "Cameroon",
  "Canada",
  "China",
  "Democratic Republic of the Congo",
  "Egypt",
  "Eswatini",
  "Ethiopia",
  "France",
  "Germany",
  "Ghana",
  "India",
  "Ireland",
  "Italy",
  "Japan",
  "Kenya",
  "Lesotho",
  "Malawi",
  "Mauritius",
  "Mozambique",
  "Namibia",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Pakistan",
  "Portugal",
  "Rwanda",
  "Saudi Arabia",
  "Senegal",
  "Sierra Leone",
  "Singapore",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Tanzania",
  "Uganda",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Zambia",
  "Zimbabwe",
] as const;

export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  Algeria: ["Algiers", "Oran", "Constantine"],
  Angola: ["Luanda", "Huambo", "Lubango"],
  Argentina: ["Buenos Aires", "Cordoba", "Rosario"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth"],
  Bangladesh: ["Dhaka", "Chattogram", "Khulna"],
  Belgium: ["Brussels", "Antwerp", "Ghent"],
  Botswana: ["Gaborone", "Francistown", "Maun"],
  Brazil: ["Sao Paulo", "Rio de Janeiro", "Brasilia"],
  Cameroon: ["Yaounde", "Douala", "Bamenda"],
  Canada: ["Toronto", "Vancouver", "Montreal", "Calgary"],
  China: ["Beijing", "Shanghai", "Shenzhen", "Guangzhou"],
  "Democratic Republic of the Congo": ["Kinshasa", "Lubumbashi", "Goma"],
  Egypt: ["Cairo", "Alexandria", "Giza"],
  Eswatini: ["Mbabane", "Manzini"],
  Ethiopia: ["Addis Ababa", "Dire Dawa", "Mekelle"],
  France: ["Paris", "Lyon", "Marseille"],
  Germany: ["Berlin", "Munich", "Hamburg", "Frankfurt"],
  Ghana: ["Accra", "Kumasi", "Takoradi"],
  India: ["Mumbai", "Delhi", "Bengaluru", "Chennai", "Hyderabad"],
  Ireland: ["Dublin", "Cork", "Galway"],
  Italy: ["Rome", "Milan", "Naples"],
  Japan: ["Tokyo", "Osaka", "Yokohama"],
  Kenya: ["Nairobi", "Mombasa", "Kisumu", "Nakuru"],
  Lesotho: ["Maseru", "Teyateyaneng"],
  Malawi: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Mangochi"],
  Mauritius: ["Port Louis", "Curepipe", "Vacoas-Phoenix"],
  Mozambique: ["Maputo", "Beira", "Nampula", "Tete"],
  Namibia: ["Windhoek", "Walvis Bay", "Rundu"],
  Netherlands: ["Amsterdam", "Rotterdam", "The Hague"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch"],
  Nigeria: ["Lagos", "Abuja", "Kano", "Port Harcourt"],
  Pakistan: ["Karachi", "Lahore", "Islamabad"],
  Portugal: ["Lisbon", "Porto", "Braga"],
  Rwanda: ["Kigali", "Huye", "Musanze"],
  "Saudi Arabia": ["Riyadh", "Jeddah", "Dammam"],
  Senegal: ["Dakar", "Touba", "Thies"],
  "Sierra Leone": ["Freetown", "Bo", "Kenema"],
  Singapore: ["Singapore"],
  Somalia: ["Mogadishu", "Hargeisa", "Kismayo"],
  "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Gqeberha"],
  "South Sudan": ["Juba", "Wau", "Malakal"],
  Spain: ["Madrid", "Barcelona", "Valencia"],
  Tanzania: ["Dar es Salaam", "Dodoma", "Arusha", "Mwanza"],
  Uganda: ["Kampala", "Entebbe", "Jinja", "Gulu"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah"],
  "United Kingdom": ["London", "Manchester", "Birmingham", "Edinburgh"],
  "United States": ["New York", "Los Angeles", "Chicago", "Houston", "Atlanta"],
  Zambia: ["Lusaka", "Ndola", "Kitwe", "Livingstone"],
  Zimbabwe: ["Harare", "Bulawayo", "Mutare", "Gweru"],
};

export { FIELDS_OF_STUDY };
