/**
 * Extra job titles — every common title that ESCO / O*NET may not surface.
 * These are grouped by generic families (not industry-scoped) so they
 * appear in any taxonomy search regardless of the selected industry.
 */

// [familyName, titleNames[]]
export const EXTRA_TITLE_ROWS: [string, string[]][] = [
  // ── Operations & Depot ──────────────────────────────────────────────
  [
    "Operations",
    [
      "Operations Manager",
      "Operations Officer",
      "Operations Coordinator",
      "Operations Director",
      "Operations Supervisor",
      "Operations Analyst",
      "Operations Lead",
      "Operations Specialist",
      "Chief Operations Officer",
      "Depot Manager",
      "Depot Officer",
      "Depot Supervisor",
      "Depot Coordinator",
      "Warehouse Depot Manager",
      "Distribution Centre Manager",
      "Distribution Supervisor",
      "Distribution Coordinator",
      "Distribution Officer",
      "Logistics Operations Manager",
      "Logistics Officer",
      "Logistics Manager",
      "Logistics Coordinator",
      "Logistics Supervisor",
      "Supply Chain Manager",
      "Supply Chain Officer",
      "Supply Chain Coordinator",
      "Supply Chain Analyst",
      "Procurement Manager",
      "Procurement Officer",
      "Procurement Coordinator",
      "Purchasing Manager",
      "Purchasing Officer",
      "Store Manager",
      "Stores Manager",
      "Stores Officer",
      "Stores Supervisor",
      "Stores Clerk",
      "Inventory Manager",
      "Inventory Officer",
      "Inventory Controller",
      "Inventory Analyst",
      "Fleet Manager",
      "Fleet Officer",
      "Fleet Coordinator",
      "Fleet Supervisor",
      "Transport Manager",
      "Transport Officer",
      "Transport Coordinator",
      "Transport Supervisor",
      "Transport Operations Manager",
      "Delivery Manager",
      "Delivery Supervisor",
      "Delivery Coordinator",
      "Route Planner",
      "Route Coordinator",
      "Dispatch Manager",
      "Dispatch Officer",
      "Dispatch Coordinator",
      "Loading Supervisor",
      "Receiving Officer",
      "Dispatch Supervisor",
      "Freight Manager",
      "Freight Coordinator",
      "Freight Officer",
      "Shipping Manager",
      "Shipping Officer",
      "Shipping Coordinator",
      "Clearing Agent",
      "Clearance Officer",
      "Warehouse Manager",
      "Warehouse Supervisor",
      "Warehouse Coordinator",
      "Warehouse Officer",
      "Warehouse Controller",
      "Receiving Clerk",
      "Pick and Pack Supervisor",
      "Goods Received Officer",
      "Materials Handler",
    ],
  ],

  // ── Management & Executive ──────────────────────────────────────────
  [
    "Management",
    [
      "General Manager",
      "Managing Director",
      "Chief Executive Officer",
      "Chief Financial Officer",
      "Chief Technology Officer",
      "Chief Operating Officer",
      "Chief Marketing Officer",
      "Chief Human Resources Officer",
      "Chief Information Officer",
      "Deputy General Manager",
      "Assistant General Manager",
      "Regional Manager",
      "Area Manager",
      "District Manager",
      "Branch Manager",
      "Country Manager",
      "National Manager",
      "Project Manager",
      "Programme Manager",
      "Senior Manager",
      "Junior Manager",
      "Assistant Manager",
      "Shift Manager",
      "Floor Manager",
      "Unit Manager",
      "Centre Manager",
      "Site Manager",
      "Office Manager",
      "Business Manager",
      "Account Manager",
      "Client Manager",
      "Key Account Manager",
      "Relationship Manager",
      "Portfolio Manager",
      "Engagement Manager",
      "Engagement Lead",
      "Team Leader",
      "Team Supervisor",
      "Shift Supervisor",
      "Shift Leader",
      "Section Head",
      "Department Head",
      "Department Manager",
    ],
  ],

  // ── Administration & Office ─────────────────────────────────────────
  [
    "Administration",
    [
      "Office Manager",
      "Administrative Manager",
      "Executive Assistant",
      "Personal Assistant",
      "Administrative Officer",
      "Administrative Assistant",
      "Administrative Coordinator",
      "Administrative Clerk",
      "Office Administrator",
      "Office Assistant",
      "Office Clerk",
      "Records Officer",
      "Records Clerk",
      "Filing Clerk",
      "Document Controller",
      "Receptionist",
      "Front Desk Officer",
      "Front Desk Clerk",
      "Switchboard Operator",
      "Messenger",
      "Office Attendant",
      "Protocol Officer",
      "Liaison Officer",
      "Executive Secretary",
      "Secretary",
      "Clerical Officer",
      "Clerical Assistant",
      "Data Entry Clerk",
      "Typist",
      "Office Boy",
    ],
  ],

  // ── Finance & Accounting ────────────────────────────────────────────
  [
    "Finance",
    [
      "Chief Financial Officer",
      "Finance Manager",
      "Finance Director",
      "Finance Officer",
      "Finance Coordinator",
      "Finance Controller",
      "Financial Analyst",
      "Financial Advisor",
      "Financial Planner",
      "Senior Accountant",
      "Accountant",
      "Accounts Officer",
      "Accounts Assistant",
      "Accounts Clerk",
      "Assistant Accountant",
      "Management Accountant",
      "Cost Accountant",
      "Tax Accountant",
      "Auditor",
      "Internal Auditor",
      "External Auditor",
      "Audit Manager",
      "Audit Officer",
      "Credit Controller",
      "Credit Officer",
      "Credit Analyst",
      "Treasury Manager",
      "Treasury Officer",
      "Treasury Analyst",
      "Payroll Manager",
      "Payroll Officer",
      "Payroll Clerk",
      "Payroll Administrator",
      "Billing Officer",
      "Billing Clerk",
      "Revenue Officer",
      "Revenue Manager",
      "Revenue Analyst",
      "Grants Accountant",
      "Budget Officer",
      "Budget Analyst",
      "Budget Manager",
      "Bookkeeper",
      "Cashier",
      "Cash Office Officer",
      "Petty Cash Officer",
      "Fiscal Officer",
      "Financial Reporting Officer",
      "Investment Analyst",
      "Investment Manager",
    ],
  ],

  // ── Human Resources ─────────────────────────────────────────────────
  [
    "Human Resources",
    [
      "Chief Human Resources Officer",
      "Human Resources Manager",
      "Human Resources Director",
      "Human Resources Officer",
      "Human Resources Coordinator",
      "Human Resources Assistant",
      "Human Resources Administrator",
      "HR Business Partner",
      "Senior HR Officer",
      "Recruitment Manager",
      "Recruitment Officer",
      "Recruitment Coordinator",
      "Talent Acquisition Manager",
      "Talent Acquisition Specialist",
      "Talent Officer",
      "Talent Coordinator",
      "Staff Welfare Officer",
      "Employee Relations Officer",
      "Employee Relations Manager",
      "Compensation and Benefits Officer",
      "Compensation Manager",
      "Benefits Administrator",
      "Learning and Development Manager",
      "Learning and Development Officer",
      "Training Manager",
      "Training Officer",
      "Training Coordinator",
      "Training Facilitator",
      "Training Administrator",
      "Organisational Development Officer",
      "Performance Management Officer",
      "Industrial Relations Officer",
      "Labour Relations Officer",
      "Workforce Planning Officer",
      "HR Analyst",
      "HRIS Administrator",
      "Employee Wellness Officer",
      "Diversity and Inclusion Officer",
      "Labour Officer",
    ],
  ],

  // ── Information Technology ──────────────────────────────────────────
  [
    "Information Technology",
    [
      "Chief Information Officer",
      "Chief Technology Officer",
      "IT Manager",
      "IT Director",
      "IT Officer",
      "IT Coordinator",
      "IT Administrator",
      "IT Support Officer",
      "IT Support Technician",
      "IT Help Desk Analyst",
      "Service Desk Analyst",
      "Desktop Support Technician",
      "Systems Administrator",
      "Network Administrator",
      "Network Engineer",
      "Network Technician",
      "Server Administrator",
      "Cloud Engineer",
      "Cloud Architect",
      "DevOps Engineer",
      "Site Reliability Engineer",
      "Security Analyst",
      "Security Engineer",
      "Security Architect",
      "Information Security Officer",
      "Software Developer",
      "Software Engineer",
      "Software Architect",
      "Full Stack Developer",
      "Frontend Developer",
      "Backend Developer",
      "Mobile Developer",
      "Web Developer",
      "UI Developer",
      "QA Engineer",
      "Quality Assurance Engineer",
      "Test Engineer",
      "Automation Engineer",
      "Data Engineer",
      "Data Analyst",
      "Data Scientist",
      "Database Administrator",
      "BI Developer",
      "Business Intelligence Analyst",
      "AI Engineer",
      "Machine Learning Engineer",
      "CRM Administrator",
      "ERP Administrator",
      "Systems Analyst",
      "Business Analyst",
      "Technical Analyst",
      "Technical Writer",
      "Solutions Architect",
      "Integration Specialist",
      "GIS Specialist",
      "GIS Analyst",
      "Geographic Information Systems Officer",
      "Scrum Master",
      "Agile Coach",
      "Product Owner",
      "Product Manager",
      "Platform Engineer",
      "Infrastructure Engineer",
      "Fibre Technician",
      "Cabling Technician",
      "IT Procurement Officer",
      "ICT Manager",
      "ICT Officer",
    ],
  ],

  // ── Sales & Marketing ───────────────────────────────────────────────
  [
    "Sales",
    [
      "Sales Manager",
      "Sales Director",
      "Sales Officer",
      "Sales Coordinator",
      "Sales Executive",
      "Sales Representative",
      "Senior Sales Representative",
      "Inside Sales Representative",
      "Outside Sales Representative",
      "Area Sales Manager",
      "Regional Sales Manager",
      "National Sales Manager",
      "Key Account Manager",
      "Key Account Executive",
      "Business Development Manager",
      "Business Development Officer",
      "Business Development Executive",
      "Business Development Representative",
      "Account Executive",
      "Account Representative",
      "Client Relationship Manager",
      "Telesales Executive",
      "Telesales Officer",
      "Telemarketer",
      "Sales Analyst",
      "Sales Administrator",
      "Sales Assistant",
      "Sales Consultant",
      "Sales Promoter",
      "Retail Manager",
      "Retail Supervisor",
      "Retail Assistant",
      "Retail Analyst",
      "Shop Manager",
      "Shop Assistant",
      "Store Manager",
      "Store Supervisor",
      "Merchandiser",
      "Merchandising Manager",
      "Merchandising Coordinator",
      "Visual Merchandiser",
      "Brand Manager",
      "Brand Ambassador",
      "Trade Marketing Officer",
      "Trade Marketing Manager",
      "Channel Manager",
      "Channel Sales Officer",
      "Distribution Sales Officer",
      "Wholesale Manager",
    ],
  ],

  // ── Marketing & Communications ──────────────────────────────────────
  [
    "Marketing",
    [
      "Chief Marketing Officer",
      "Marketing Manager",
      "Marketing Director",
      "Marketing Officer",
      "Marketing Coordinator",
      "Marketing Assistant",
      "Marketing Analyst",
      "Marketing Specialist",
      "Digital Marketing Manager",
      "Digital Marketing Officer",
      "Digital Marketing Specialist",
      "Digital Marketing Executive",
      "SEO Specialist",
      "SEO Manager",
      "SEM Specialist",
      "PPC Specialist",
      "Content Marketing Manager",
      "Content Creator",
      "Content Writer",
      "Content Strategist",
      "Social Media Manager",
      "Social Media Officer",
      "Social Media Specialist",
      "Social Media Coordinator",
      "Community Manager",
      "Community Officer",
      "Email Marketing Specialist",
      "Campaign Manager",
      "Campaign Coordinator",
      "Campaign Officer",
      "Brand Manager",
      "Brand Officer",
      "Public Relations Manager",
      "Public Relations Officer",
      "Public Relations Specialist",
      "Communications Manager",
      "Communications Officer",
      "Communications Specialist",
      "Corporate Communications Officer",
      "Media Relations Officer",
      "Media Planner",
      "Media Buyer",
      "Advertising Manager",
      "Advertising Officer",
      "Creative Manager",
      "Creative Director",
      "Creative Officer",
      "Graphic Designer",
      "Visual Designer",
      "UI Designer",
      "UX Designer",
      "UX Researcher",
      "Web Designer",
      "Video Producer",
      "Video Editor",
      "Photographer",
      "Videographer",
      "Animator",
      "Motion Graphics Designer",
      "Copywriter",
      "Publicist",
      "Spokesperson",
    ],
  ],

  // ── Customer Service ────────────────────────────────────────────────
  [
    "Customer Service",
    [
      "Customer Service Manager",
      "Customer Service Director",
      "Customer Service Officer",
      "Customer Service Representative",
      "Customer Service Agent",
      "Customer Service Supervisor",
      "Customer Service Coordinator",
      "Customer Service Lead",
      "Customer Support Manager",
      "Customer Support Officer",
      "Customer Support Specialist",
      "Customer Success Manager",
      "Customer Success Officer",
      "Client Service Manager",
      "Client Service Officer",
      "Client Service Representative",
      "Help Desk Officer",
      "Help Desk Analyst",
      "Service Desk Analyst",
      "Call Centre Manager",
      "Call Centre Supervisor",
      "Call Centre Team Leader",
      "Call Centre Agent",
      "Contact Centre Agent",
      "Contact Centre Manager",
      "Complaints Officer",
      "Complaints Handler",
      "Dispute Resolution Officer",
      "Escalations Specialist",
      "Feedback Officer",
      "Satisfaction Officer",
    ],
  ],

  // ── Legal ───────────────────────────────────────────────────────────
  [
    "Legal",
    [
      "Legal Manager",
      "Legal Director",
      "Legal Officer",
      "Legal Counsel",
      "Senior Legal Counsel",
      "General Counsel",
      "Company Secretary",
      "Corporate Secretary",
      "Legal Advisor",
      "Legal Assistant",
      "Paralegal",
      "Legal Clerk",
      "Compliance Manager",
      "Compliance Officer",
      "Compliance Analyst",
      "Regulatory Affairs Officer",
      "Regulatory Affairs Manager",
      "Governance Officer",
      "Governance Manager",
      "Risk Manager",
      "Risk Officer",
      "Risk Analyst",
      "Contracts Manager",
      "Contracts Officer",
      "Contracts Administrator",
      "Intellectual Property Officer",
      "Trademark Officer",
      "Patent Officer",
      "Litigation Manager",
      "Dispute Resolution Manager",
      "Arbitrator",
      "Mediator",
      "Notary Public",
      "Legal Researcher",
      "Policy Officer",
      "Policy Analyst",
      "Policy Advisor",
      "Policy Manager",
    ],
  ],

  // ── Health & Medical ────────────────────────────────────────────────
  [
    "Healthcare",
    [
      "Medical Officer",
      "Medical Director",
      "Chief Medical Officer",
      "Clinical Officer",
      "General Practitioner",
      "Family Physician",
      "Specialist Doctor",
      "Surgeon",
      "Paediatrician",
      "Obstetrician",
      "Gynaecologist",
      "Cardiologist",
      "Dermatologist",
      "Ophthalmologist",
      "Orthopaedic Surgeon",
      "ENT Specialist",
      "Psychiatrist",
      "Neurologist",
      "Radiologist",
      "Anaesthesiologist",
      "Pathologist",
      "Physiotherapist",
      "Physiotherapy Assistant",
      "Occupational Therapist",
      "Speech Therapist",
      "Dietitian",
      "Nutritionist",
      "Pharmacist",
      "Pharmacy Manager",
      "Pharmacy Technician",
      "Pharmacy Assistant",
      "Dispensary Technician",
      "Nursing Manager",
      "Nursing Officer",
      "Registered Nurse",
      "Enrolled Nurse",
      "Nurse Midwife Technician",
      "Midwife",
      "Community Health Nurse",
      "Theatre Nurse",
      "Paediatric Nurse",
      "Mental Health Nurse",
      "Dental Officer",
      "Dentist",
      "Dental Technician",
      "Dental Hygienist",
      "Dental Assistant",
      "Laboratory Manager",
      "Laboratory Scientist",
      "Laboratory Technician",
      "Laboratory Assistant",
      "Medical Laboratory Technologist",
      "Radiographer",
      "X-ray Technician",
      "Ultrasound Technician",
      "Medical Records Officer",
      "Health Records Officer",
      "Health Information Manager",
      "Infection Control Officer",
      "Environmental Health Officer",
      "Health Promotion Officer",
      "Community Health Worker",
      "Community Health Extension Worker",
      "Health Surveillance Assistant",
      "HIV/AIDS Officer",
      "Malaria Programme Officer",
      "Maternal Health Officer",
      "Child Health Officer",
      "Epidemiologist",
      "Public Health Officer",
      "Public Health Specialist",
      "Health Systems Manager",
      "Hospital Administrator",
      "Hospital Manager",
      "Medical Records Clerk",
      "Patient Registrar",
      "Admissions Officer",
      "Ward Manager",
      "Ward Clerk",
      "Ward Attendant",
      "Mortuary Technician",
      "Optometrist",
      "Orthoptist",
      "Audiologist",
      "Prosthetist",
      "Orthotist",
      "Massage Therapist",
      "Medical Illustrator",
      "Health and Safety Officer",
      "Medical Sales Representative",
      "Pharmaceutical Sales Representative",
      "Clinical Research Coordinator",
      "Clinical Research Associate",
    ],
  ],

  // ── Education ───────────────────────────────────────────────────────
  [
    "Education",
    [
      "University Professor",
      "Associate Professor",
      "Assistant Professor",
      "Lecturer",
      "Senior Lecturer",
      "Head of Department",
      "Dean of Faculty",
      "Vice Chancellor",
      "Rector",
      "Principal",
      "Vice Principal",
      "Head Teacher",
      "Headmaster",
      "Headmistress",
      "School Principal",
      "Deputy Principal",
      "School Administrator",
      "Education Officer",
      "Curriculum Developer",
      "Curriculum Specialist",
      "Examination Officer",
      "Academic Officer",
      "Academic Advisor",
      "Research Officer",
      "Research Fellow",
      "Postdoctoral Researcher",
      "Teaching Assistant",
      "Graduate Assistant",
      "Pre School Teacher",
      "Primary School Teacher",
      "Secondary School Teacher",
      "Special Education Teacher",
      "Inclusive Education Teacher",
      "Adult Education Teacher",
      "Literacy Teacher",
      "Numeracy Teacher",
      "School Counselor",
      "Guidance Counselor",
      "Student Affairs Officer",
      "Student Support Officer",
      "Student Welfare Officer",
      "Registrar",
      "Examinations Coordinator",
      "School Bursar",
      "Librarian",
      "School Librarian",
      "Laboratory Teacher",
      "ICT Teacher",
      "Sports Teacher",
      "Music Teacher",
      "Art Teacher",
      "Language Teacher",
      "English Teacher",
      "French Teacher",
      "Chichewa Teacher",
      "Mathematics Teacher",
      "Science Teacher",
      "Physics Teacher",
      "Chemistry Teacher",
      "Biology Teacher",
      "History Teacher",
      "Geography Teacher",
      "Economics Teacher",
    ],
  ],

  // ── Engineering ─────────────────────────────────────────────────────
  [
    "Engineering",
    [
      "Chief Engineer",
      "Senior Engineer",
      "Engineer",
      "Junior Engineer",
      "Graduate Engineer",
      "Engineering Manager",
      "Engineering Director",
      "Civil Engineer",
      "Senior Civil Engineer",
      "Structural Engineer",
      "Geotechnical Engineer",
      "Transportation Engineer",
      "Highway Engineer",
      "Water Resources Engineer",
      "Environmental Engineer",
      "Mechanical Engineer",
      "Senior Mechanical Engineer",
      "Automotive Engineer",
      "Aeronautical Engineer",
      "Electrical Engineer",
      "Senior Electrical Engineer",
      "Electronics Engineer",
      "Telecommunications Engineer",
      "Instrumentation Engineer",
      "Control Systems Engineer",
      "Chemical Engineer",
      "Process Engineer",
      "Industrial Engineer",
      "Manufacturing Engineer",
      "Production Engineer",
      "Quality Engineer",
      "Reliability Engineer",
      "Safety Engineer",
      "Mining Engineer",
      "Petroleum Engineer",
      "Metallurgical Engineer",
      "Materials Engineer",
      "Biomedical Engineer",
      "Agricultural Engineer",
      "Food Engineer",
      "Energy Engineer",
      "Renewable Energy Engineer",
      "Solar Engineer",
      "Wind Engineer",
      "Network Engineer",
      "Software Engineer",
      "Systems Engineer",
      "Solutions Engineer",
      "Sales Engineer",
      "Field Engineer",
      "Project Engineer",
      "Maintenance Engineer",
      "Plant Engineer",
      "Facilities Engineer",
      "Maintenance Planner",
      "Maintenance Supervisor",
      "Maintenance Manager",
      "Maintenance Technician",
      "Boiler Technician",
      "HVAC Technician",
      "Plumber",
      "Electrician",
      "Carpenter",
      "Welder",
      "Fitter and Turner",
      "Millwright",
      "Rigger",
      "Scaffolder",
      "Crane Operator",
      "Forklift Operator",
      "Plant Operator",
      "Heavy Equipment Operator",
    ],
  ],

  // ── Construction & Real Estate ──────────────────────────────────────
  [
    "Construction",
    [
      "Construction Manager",
      "Construction Director",
      "Construction Supervisor",
      "Construction Foreman",
      "Construction Project Manager",
      "Construction Superintendent",
      "Site Manager",
      "Site Supervisor",
      "Site Foreman",
      "Site Engineer",
      "Site Clerk",
      "Quantity Surveyor",
      "Building Surveyor",
      "Valuer",
      "Property Valuer",
      "Estate Surveyor",
      "Land Surveyor",
      "Surveyor",
      "Geomatics Engineer",
      "Architect",
      "Senior Architect",
      "Landscape Architect",
      "Urban Planner",
      "Town Planner",
      "Regional Planner",
      "Interior Designer",
      "Interior Decorator",
      "CAD Technician",
      "Draughtsperson",
      "Technical Draughtsperson",
      "BIM Manager",
      "BIM Coordinator",
      "BIM Technician",
      "Construction Estimator",
      "Cost Estimator",
      "Procurement Officer",
      "Building Inspector",
      "Planning Officer",
      "Property Manager",
      "Facilities Manager",
      "Facilities Officer",
      "Building Manager",
      "Estate Manager",
      "Mall Manager",
    ],
  ],

  // ── Agriculture & Food ──────────────────────────────────────────────
  [
    "Agriculture",
    [
      "Agricultural Manager",
      "Agricultural Officer",
      "Agricultural Extension Officer",
      "Agricultural Extension Worker",
      "Farm Manager",
      "Assistant Farm Manager",
      "Farm Supervisor",
      "Farm Foreman",
      "Farm Worker",
      "Estate Manager",
      "Estate Supervisor",
      "Field Supervisor",
      "Field Officer",
      "Field Coordinator",
      "Agronomist",
      "Senior Agronomist",
      "Crop Scientist",
      "Soil Scientist",
      "Plant Scientist",
      "Horticulturist",
      "Horticulture Manager",
      "Arborist",
      "Livestock Manager",
      "Livestock Officer",
      "Animal Scientist",
      "Veterinarian",
      "Veterinary Officer",
      "Veterinary Technician",
      "Animal Health Technician",
      "Poultry Manager",
      "Dairy Manager",
      "Fisheries Officer",
      "Aquaculture Manager",
      "Beekeeper",
      "Food Technologist",
      "Food Scientist",
      "Food Safety Officer",
      "Quality Assurance Manager",
      "Quality Control Officer",
      "Food Processing Manager",
      "Cold Chain Manager",
      "Agribusiness Manager",
      "Agribusiness Officer",
      "Agricultural Economist",
      "Agricultural Engineer",
      "Irrigation Engineer",
      "Irrigation Technician",
      "Mechanisation Officer",
    ],
  ],

  // ── Hospitality & Tourism ───────────────────────────────────────────
  [
    "Hospitality",
    [
      "Hotel Manager",
      "Hotel General Manager",
      "Hotel Administrator",
      "Front Office Manager",
      "Front Office Supervisor",
      "Front Desk Officer",
      "Night Manager",
      "Duty Manager",
      "Housekeeping Manager",
      "Housekeeping Supervisor",
      "Laundry Manager",
      "Concierge",
      "Guest Relations Manager",
      "Revenue Manager",
      "Food and Beverage Manager",
      "Food and Beverage Director",
      "Restaurant Manager",
      "Restaurant Supervisor",
      "Restaurant Host",
      "Bar Manager",
      "Bar Supervisor",
      "Barista",
      "Bartender",
      "Head Chef",
      "Executive Chef",
      "Chef",
      "Sous Chef",
      "Pastry Chef",
      "Pastry Cook",
      "Commis Chef",
      "Kitchen Porter",
      "Kitchen Manager",
      "Catering Manager",
      "Catering Coordinator",
      "Events Manager",
      "Events Coordinator",
      "Banquet Manager",
      "Wedding Coordinator",
      "Conference Manager",
      "Tour Guide",
      "Tour Coordinator",
      "Tourism Officer",
      "Travel Consultant",
      "Travel Agent",
      "Travel Coordinator",
      "Safari Guide",
      "Lodge Manager",
      "Guest House Manager",
      "Airline Manager",
      "Ground Handling Officer",
      "Aviation Operations Manager",
      "Passenger Handling Agent",
    ],
  ],

  // ── Banking & Finance ───────────────────────────────────────────────
  [
    "Banking",
    [
      "Bank Manager",
      "Branch Manager",
      "Branch Supervisor",
      "Assistant Branch Manager",
      "Bank Teller",
      "Senior Bank Teller",
      "Cashier",
      "Customer Service Officer",
      "Relationship Manager",
      "Personal Banker",
      "Corporate Banker",
      "Investment Banker",
      "Investment Manager",
      "Wealth Manager",
      "Portfolio Manager",
      "Fund Manager",
      "Equity Analyst",
      "Fixed Income Analyst",
      "Treasury Manager",
      "Treasury Officer",
      "Foreign Exchange Dealer",
      "Credit Analyst",
      "Credit Manager",
      "Loan Officer",
      "Loan Processing Officer",
      "Mortgage Officer",
      "Risk Manager",
      "Risk Analyst",
      "Credit Risk Officer",
      "Operational Risk Officer",
      "Market Risk Analyst",
      "Compliance Manager",
      "Compliance Officer",
      "AML Officer",
      "Anti Money Laundering Officer",
      "Fraud Investigator",
      "Internal Control Officer",
      "Forex Trader",
      "Securities Trader",
      "Stockbroker",
      "Insurance Agent",
      "Insurance Broker",
      "Insurance Underwriter",
      "Claims Manager",
      "Claims Officer",
      "Claims Assessor",
      "Actuary",
      "Pension Fund Manager",
      "Microfinance Officer",
      "Microfinance Manager",
      "Mobile Money Agent",
      "Mobile Money Officer",
      "Agency Banking Officer",
    ],
  ],

  // ── Security ────────────────────────────────────────────────────────
  [
    "Security",
    [
      "Security Manager",
      "Security Director",
      "Security Operations Manager",
      "Security Supervisor",
      "Security Team Leader",
      "Security Officer",
      "Security Guard",
      "Armed Response Officer",
      "Access Control Officer",
      "CCTV Operator",
      "Surveillance Officer",
      "Intelligence Officer",
      "Investigator",
      "Private Investigator",
      "Fraud Investigator",
      "Fraud Examiner",
      "Loss Prevention Officer",
      "Loss Prevention Manager",
      "Cybersecurity Analyst",
      "Cybersecurity Engineer",
      "Penetration Tester",
      "Security Architect",
      "Forensic Analyst",
      "Digital Forensics Investigator",
      "Risk Assessment Officer",
      "Safety Officer",
      "Health and Safety Manager",
      "Health and Safety Officer",
      "Environmental Health and Safety Officer",
      "Fire Safety Officer",
      "Firefighter",
      "Emergency Response Officer",
      "Crisis Manager",
      "Business Continuity Manager",
      "Disaster Recovery Manager",
      "Close Protection Officer",
      "Personal Security Officer",
      "VIP Protection Officer",
      "Crowd Control Officer",
    ],
  ],

  // ── Media & Creative ────────────────────────────────────────────────
  [
    "Media",
    [
      "Journalist",
      "Senior Journalist",
      "Editor",
      "Managing Editor",
      "News Editor",
      "Features Editor",
      "Sub Editor",
      "Copy Editor",
      "Reporter",
      "Correspondent",
      "Foreign Correspondent",
      "Bureau Chief",
      "News Anchor",
      "Presenter",
      "Radio Presenter",
      "Television Presenter",
      "Broadcast Journalist",
      "Photojournalist",
      "Camera Operator",
      "Video Journalist",
      "Freelance Journalist",
      "Columnist",
      "Blogger",
      "Influencer Manager",
      "Podcast Producer",
      "Podcast Host",
      "Radio Producer",
      "Radio Station Manager",
      "TV Producer",
      "Film Producer",
      "Film Director",
      "Screenwriter",
      "Scriptwriter",
      "Production Manager",
      "Production Coordinator",
      "Production Assistant",
      "Stage Manager",
      "Lighting Technician",
      "Sound Engineer",
      "Audio Engineer",
      "Recording Engineer",
      "Mastering Engineer",
      "Printing Press Operator",
      "Prepress Technician",
      "Print Production Manager",
      "Publishing Manager",
      "Editorial Manager",
    ],
  ],

  // ── Nonprofit & Development ─────────────────────────────────────────
  [
    "Development",
    [
      "Country Director",
      "Programme Director",
      "Programme Manager",
      "Senior Programme Manager",
      "Programme Officer",
      "Programme Coordinator",
      "Project Director",
      "Project Manager",
      "Senior Project Manager",
      "Project Officer",
      "Project Coordinator",
      "Project Assistant",
      "Field Coordinator",
      "Field Manager",
      "Field Officer",
      "Field Supervisor",
      "Area Coordinator",
      "District Coordinator",
      "Monitoring and Evaluation Manager",
      "M&E Officer",
      "M&E Coordinator",
      "M&E Specialist",
      "Research and Evaluation Officer",
      "Grants Manager",
      "Grants Officer",
      "Grants Coordinator",
      "Donor Relations Officer",
      "Fundraising Manager",
      "Fundraising Officer",
      "Resource Mobilisation Officer",
      "Resource Mobilisation Manager",
      "Communications Manager",
      "Advocacy Officer",
      "Advocacy Manager",
      "Policy and Advocacy Officer",
      "Humanitarian Coordinator",
      "Emergency Programme Manager",
      "Child Protection Officer",
      "Gender Officer",
      "Gender Mainstreaming Officer",
      "GBV Officer",
      "Protection Officer",
      "Resilience Officer",
      "Climate Change Officer",
      "Sustainability Manager",
      "Sustainability Officer",
      "WASH Officer",
      "Nutrition Officer",
      "Food Security Officer",
      "Livelihoods Officer",
      "Shelter Officer",
      "Logistics and Operations Manager",
      "Supply Chain and Logistics Officer",
      "Procurement and Logistics Manager",
      "Administration and Finance Manager",
      "Operations and Finance Manager",
      "MEAL Coordinator",
      "Capacity Building Officer",
      "Knowledge Management Officer",
      "Reporting Officer",
      "Compliance Officer",
      "Internal Auditor",
    ],
  ],

  // ── Environmental & Conservation ────────────────────────────────────
  [
    "Environment",
    [
      "Environmental Manager",
      "Environmental Officer",
      "Environmental Scientist",
      "Environmental Engineer",
      "Environmental Consultant",
      "Environmental Analyst",
      "Environmental Planner",
      "Environmental Impact Assessment Specialist",
      "EIA Specialist",
      "Conservation Manager",
      "Conservation Officer",
      "Conservation Scientist",
      "Wildlife Officer",
      "Wildlife Manager",
      "Wildlife Biologist",
      "Park Ranger",
      "Game Ranger",
      "Protected Areas Manager",
      "Forestry Officer",
      "Forestry Manager",
      "Forest Ranger",
      "Climate Change Specialist",
      "Climate Change Analyst",
      "Carbon Trading Officer",
      "Renewable Energy Specialist",
      "Energy Manager",
      "Energy Auditor",
      "Waste Management Officer",
      "Waste Management Manager",
      "Recycling Officer",
      "Water Quality Officer",
      "Water Resources Manager",
      "Hydrologist",
      "Geologist",
      "Geophysicist",
      "Seismologist",
      "Cartographer",
      "Remote Sensing Specialist",
      "GIS Manager",
      "Land Use Planner",
    ],
  ],

  // ── Transport & Fleet (specific titles the user asked for) ──────────
  [
    "Transport",
    [
      "Transport Manager",
      "Transport Director",
      "Transport Officer",
      "Transport Coordinator",
      "Transport Supervisor",
      "Fleet Manager",
      "Fleet Director",
      "Fleet Officer",
      "Fleet Coordinator",
      "Fleet Supervisor",
      "Fleet Analyst",
      "Fleet Administrator",
      "Fleet Controller",
      "Depot Manager",
      "Depot Supervisor",
      "Depot Coordinator",
      "Depot Officer",
      "Depot Attendant",
      "Logistics Manager",
      "Logistics Director",
      "Logistics Officer",
      "Logistics Coordinator",
      "Logistics Supervisor",
      "Logistics Analyst",
      "Supply Chain Manager",
      "Supply Chain Director",
      "Supply Chain Officer",
      "Supply Chain Analyst",
      "Warehouse Manager",
      "Warehouse Supervisor",
      "Warehouse Coordinator",
      "Warehouse Officer",
      "Distribution Manager",
      "Distribution Supervisor",
      "Distribution Officer",
      "Distribution Coordinator",
      "Delivery Manager",
      "Delivery Supervisor",
      "Delivery Coordinator",
      "Dispatch Manager",
      "Dispatch Supervisor",
      "Dispatch Officer",
      "Route Manager",
      "Route Coordinator",
      "Route Planner",
      "Freight Manager",
      "Freight Coordinator",
      "Freight Officer",
      "Shipping Manager",
      "Shipping Coordinator",
      "Customs Officer",
      "Customs Clearing Agent",
      "Clearing and Forwarding Agent",
      "Port Manager",
      "Port Operations Manager",
      "Port Operations Officer",
      "Terminal Manager",
      "Yard Manager",
      "Loading Supervisor",
      "Driver",
      "HGV Driver",
      "PSV Driver",
      "Motorbike Courier",
      "Pilot",
      "Captain",
      "First Officer",
      "Air Traffic Controller",
      "Ground Handling Officer",
      "Marine Engineer",
      "Deck Officer",
    ],
  ],

  // ── Energy & Utilities ──────────────────────────────────────────────
  [
    "Energy",
    [
      "Energy Manager",
      "Energy Director",
      "Power Plant Manager",
      "Power Station Operator",
      "Power Systems Engineer",
      "Power Systems Operator",
      "Electrical Engineer",
      "Electrical Supervisor",
      "Electrical Technician",
      "Electrical Installer",
      "Lineman",
      "Power Line Technician",
      "Substation Operator",
      "Grid Manager",
      "Grid Operator",
      "Solar Installation Technician",
      "Solar Engineer",
      "Solar PV Installer",
      "Solar Project Manager",
      "Wind Farm Manager",
      "Wind Turbine Technician",
      "Hydro Power Engineer",
      "Bioenergy Engineer",
      "Energy Auditor",
      "Energy Consultant",
      "Energy Analyst",
      "Metering Technician",
      "Water Treatment Plant Operator",
      "Water and Sanitation Officer",
      "Water Engineer",
      "Sanitation Officer",
      "Plumbing Supervisor",
      "Plumber",
      "Gas Technician",
      "Fuel Station Manager",
      "Petroleum Officer",
    ],
  ],

  // ── Telecommunications ──────────────────────────────────────────────
  [
    "Telecommunications",
    [
      "Telecommunications Manager",
      "Telecommunications Engineer",
      "Telecommunications Technician",
      "Network Operations Manager",
      "Network Operations Centre Technician",
      "NOC Technician",
      "Network Engineer",
      "Senior Network Engineer",
      "Network Architect",
      "Network Analyst",
      "Network Planner",
      "Field Service Engineer",
      "Field Service Technician",
      "Site Engineer",
      "Tower Technician",
      "Tower Climber",
      "Fibre Optic Technician",
      "Fibre Engineer",
      " fibre optic splicer",
      "Cable Jointer",
      "Radio Technician",
      "Microwave Engineer",
      "Satellite Communications Engineer",
      "ISP Technician",
      "Broadband Technician",
      "Telecom Sales Officer",
      "Mobile Money Agent",
      "VAS Officer",
      "Value Added Services Officer",
    ],
  ],

  // ── Government & Public Administration ───────────────────────────────
  [
    "Government",
    [
      "District Commissioner",
      "District Executive Officer",
      "District Development Officer",
      "Area Development Officer",
      "Community Development Officer",
      "Community Development Assistant",
      "Extension Planning Area Coordinator",
      "Traditional Authority Coordinator",
      "Village Headman",
      "Councillor",
      "Mayor",
      "Deputy Mayor",
      "Council Secretary",
      "Town Clerk",
      "Deputy Town Clerk",
      "Principal Secretary",
      "Under Secretary",
      "Director of Administration",
      "Director of Finance",
      "Director of Health",
      "Director of Education",
      "District Health Officer",
      "District Education Manager",
      "District Agricultural Officer",
      "District Social Welfare Officer",
      "District Labour Officer",
      "District Information Officer",
      "Revenue Officer",
      "Tax Officer",
      "Customs and Excise Officer",
      "Immigration Officer",
      "Passport Officer",
      "Civil Registry Officer",
      "National Registration Officer",
      "Electoral Officer",
      "Election Monitor",
      "Public Service Officer",
      "Administrative Secretary",
      "Government Accountant",
      "Public Procurement Officer",
      "Government Printer",
    ],
  ],

  // ── Mining & Extractives ────────────────────────────────────────────
  [
    "Mining",
    [
      "Mine Manager",
      "Mine Superintendent",
      "Mine Supervisor",
      "Mine Foreman",
      "Mining Engineer",
      "Senior Mining Engineer",
      "Mining Geologist",
      "Exploration Geologist",
      "Senior Geologist",
      "Metallurgist",
      "Process Engineer",
      "Plant Manager",
      "Plant Supervisor",
      "Mill Superintendent",
      "Mill Operator",
      "Millwright",
      "Drill Operator",
      "Blasting Officer",
      "Blasting Engineer",
      "Blasting Supervisor",
      "Explosives Handler",
      "Survey Technician",
      "Mine Safety Officer",
      "Mine Safety Engineer",
      "Environmental Officer",
      "Mine Rescue Officer",
      "Shift Boss",
      "Underground Supervisor",
      "Underground Miner",
      "Surface Miner",
      "Heavy Equipment Operator",
      "Haul Truck Driver",
      "Excavator Operator",
      "Geotechnical Engineer",
      "Mineralogist",
      "Metallurgical Technician",
      "Concentrator Operator",
      "Tailings Manager",
    ],
  ],

  // ── Aviation & Maritime ─────────────────────────────────────────────
  [
    "Aviation",
    [
      "Airport Manager",
      "Airport Operations Manager",
      "Airport Operations Officer",
      "Airport Operations Coordinator",
      "Ground Handling Manager",
      "Ground Handling Officer",
      "Passenger Service Agent",
      "Check-in Agent",
      "Gate Agent",
      "Ramp Agent",
      "Ramp Supervisor",
      "Baggage Handler",
      "Cargo Handler",
      "Cargo Manager",
      "Cargo Officer",
      "Aviation Safety Officer",
      "Flight Operations Officer",
      "Flight Dispatcher",
      "Flight Planning Officer",
      "Airline Manager",
      "Airline Sales Manager",
      "Airline Revenue Manager",
      "Airline Customer Service Agent",
      "Pilot",
      "Commercial Pilot",
      "Helicopter Pilot",
      "First Officer",
      "Flight Engineer",
      "Cabin Crew Manager",
      "Cabin Crew Member",
      "Flight Attendant",
      "Purser",
      "Aircraft Maintenance Engineer",
      "Aircraft Technician",
      "Avionics Technician",
      "Aircraft Mechanic",
      "Aircraft Painter",
      "Air Traffic Controller",
      "Air Traffic Management Officer",
    ],
  ],

  // ── Beauty & Personal Care ──────────────────────────────────────────
  [
    "Beauty",
    [
      "Salon Manager",
      "Salon Supervisor",
      "Salon Coordinator",
      "Hairdresser",
      "Hairstylist",
      "Barber",
      "Beauty Therapist",
      "Senior Beauty Therapist",
      "Nail Technician",
      "Nail Artist",
      "Spa Manager",
      "Spa Therapist",
      "Massage Therapist",
      "Reflexologist",
      "Aromatherapist",
      "Makeup Artist",
      "Skincare Specialist",
      "Esthetician",
      "Waxing Technician",
      "Lash Technician",
      "Microblading Artist",
      "Personal Trainer",
      "Fitness Coach",
      "Gym Instructor",
      "Gym Manager",
      "Wellness Coach",
      "Wellness Consultant",
      "Yoga Instructor",
      "Pilates Instructor",
    ],
  ],

  // ── Waste & Recycling ───────────────────────────────────────────────
  [
    "Waste Management",
    [
      "Waste Management Manager",
      "Waste Operations Manager",
      "Waste Collection Supervisor",
      "Waste Collection Driver",
      "Waste Collector",
      "Recycling Manager",
      "Recycling Officer",
      "Recycling Plant Operator",
      "Materials Recovery Officer",
      "Landfill Manager",
      "Landfill Operator",
      "Sanitation Inspector",
      "Environmental Health Inspector",
      "Public Health Inspector",
      "Street Cleaning Supervisor",
      "Sewage Treatment Operator",
      "Sewerage Officer",
      "Hazardous Waste Manager",
      "Hazardous Waste Handler",
      "Composting Technician",
    ],
  ],

  // ── Garments, Textiles & Fashion ────────────────────────────────────
  [
    "Fashion",
    [
      "Fashion Designer",
      "Senior Fashion Designer",
      "Assistant Fashion Designer",
      "Pattern Maker",
      "Pattern Cutter",
      "Tailor",
      "Seamstress",
      "Garment Cutter",
      "Sewing Machine Operator",
      "Garment Technician",
      "Textile Production Supervisor",
      "Textile Quality Inspector",
      "Quality Assurance Supervisor",
      "Production Supervisor",
      "Production Manager",
      "Production Planning Officer",
      "Fabric Inspector",
      "Sample Maker",
      "Production Pattern Maker",
      "Cutting Room Supervisor",
      "Ironing and Finishing Operator",
      "Fashion Merchandiser",
      "Retail Buyer",
      "Product Developer",
    ],
  ],

  // ── Printing & Publishing ───────────────────────────────────────────
  [
    "Publishing",
    [
      "Publishing Manager",
      "Editorial Manager",
      "Managing Editor",
      "Senior Editor",
      "Editor",
      "Sub Editor",
      "Copy Editor",
      "Proofreader",
      "Writer",
      "Author",
      "Content Writer",
      "Technical Writer",
      "Copywriter",
      "Journalist",
      "Senior Journalist",
      "Feature Writer",
      "Column Writer",
      "Print Production Manager",
      "Print Operator",
      "Prepress Technician",
      "Print Finisher",
      "Bookkeeper Publisher",
      "Rights Coordinator",
      "Publications Officer",
      "Digital Content Producer",
      "Web Editor",
      "Content Strategist",
    ],
  ],

  // ── Emergency & Disaster ────────────────────────────────────────────
  [
    "Emergency Services",
    [
      "Emergency Response Manager",
      "Emergency Response Officer",
      "Emergency Response Coordinator",
      "Emergency Medical Technician",
      "Paramedic",
      "Ambulance Driver",
      "Ambulance Officer",
      "Incident Commander",
      "Incident Manager",
      "Disaster Risk Reduction Officer",
      "Disaster Management Coordinator",
      "Resilience Officer",
      "Early Warning Systems Officer",
      "Search and Rescue Coordinator",
      "Search and Rescue Officer",
      "Shelter Manager",
      "Shelter Officer",
      "Relief Coordinator",
      "Relief Distribution Officer",
      "Emergency Warehouse Officer",
      "First Aid Responder",
      "Disaster Preparedness Officer",
      "Crisis Communication Officer",
    ],
  ],

  // ── Cross-Industry / Generic Titles ─────────────────────────────────
  [
    "General",
    [
      "Director",
      "Senior Director",
      "Executive Director",
      "Managing Director",
      "Deputy Director",
      "Assistant Director",
      "Head of Department",
      "Head of Unit",
      "Head of Section",
      "Chief",
      "Officer",
      "Senior Officer",
      "Junior Officer",
      "Assistant Officer",
      "Coordinator",
      "Senior Coordinator",
      "Assistant Coordinator",
      "Supervisor",
      "Senior Supervisor",
      "Team Leader",
      "Senior Team Leader",
      "Specialist",
      "Senior Specialist",
      "Expert",
      "Consultant",
      "Senior Consultant",
      "Advisor",
      "Senior Advisor",
      "Analyst",
      "Senior Analyst",
      "Associate",
      "Senior Associate",
      "Fellow",
      "Resident",
      "Intern",
      "Volunteer",
      "Ambassador",
      "Liaison Officer",
      "Special Envoy",
      "Representative",
      "Delegate",
      "Commissioner",
      "Inspector",
      "Superintendent",
      "Controller",
      "Operator",
      "Technician",
      "Senior Technician",
      "Junior Technician",
      "Mechanic",
      "Senior Mechanic",
      "Artisan",
      "Senior Artisan",
      "Apprentice",
      "Trainee",
      "Graduate Trainee",
      "Management Trainee",
      "Assistant",
      "Senior Assistant",
      "Attendant",
      "Senior Attendant",
      "Helper",
      "Labourer",
      "General Worker",
      "Watchman",
      "Cleaner",
      "Gardener",
      "Gatekeeper",
      "Janitor",
      "Porter",
      "Steward",
    ],
  ],
];

/**
 * Flat list of all extra title names for fast text search.
 * Used by the LocalProvider fallback.
 */
export const ALL_EXTRA_TITLES: string[] = EXTRA_TITLE_ROWS.flatMap(([, names]) => names);

/**
 * Search the extra titles by keyword. Returns matching titles with scores.
 */
export function searchExtraTitles(query: string, limit = 8): { label: string; score: number }[] {
  const q = query.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
  if (!q) return [];
  const terms = q.split(/\s+/).filter((t) => t.length > 1);
  if (!terms.length) return [];

  const scored: { label: string; score: number }[] = [];
  for (const label of ALL_EXTRA_TITLES) {
    const lower = label.toLowerCase();
    let score = 0;

    // Exact match
    if (lower === q) {
      score = 4;
    }
    // Starts with query
    else if (lower.startsWith(q)) {
      score = 3;
    }
    // Contains query as substring
    else if (lower.includes(q)) {
      score = 2;
    }
    // Word-level matching
    else {
      const matched = terms.filter((term) => lower.includes(term)).length;
      if (matched >= terms.length) score = 1.5;
      else if (matched >= Math.ceil(terms.length / 2)) score = 1;
      else if (matched >= 1) score = 0.5;
    }

    if (score > 0) {
      scored.push({ label, score });
    }
  }

  return scored
    .sort((a, b) => b.score - a.score || a.label.localeCompare(b.label))
    .slice(0, limit);
}
