-- Migration: Retain file_data column for base64 fallback
-- 
-- Previously this migration was planned to drop file_data after migrating
-- all documents to R2. However, file_data is still needed as a fallback
-- when R2 is not configured (local development, staging environments).
--
-- The column is retained. When R2 is configured, file_data is set to NULL
-- by uploadApplicationDocument and only file_path (the R2 key) is stored.
-- When R2 is NOT configured, file_data holds the base64-encoded file content.
--
-- This migration is now a no-op.
