/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCandidatesRouteImport } from './routes/_authenticated/candidates'
import { Route as AuthenticatedContactCenterRouteImport } from './routes/_authenticated/contact-center'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedKanbanRouteImport } from './routes/_authenticated/kanban'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as ApiPlansRouteImport } from './routes/api/plans'
import { Route as ApplyCampaignIdRouteImport } from './routes/apply.$campaignId'
import { Route as PaymentFailedRouteImport } from './routes/payment.failed'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as SessionCallbackRouteImport } from './routes/session.callback'
import { Route as SessionSignoutRouteImport } from './routes/session.signout'
import { Route as SharePublicTokenRouteImport } from './routes/share.$publicToken'
import { Route as AuthenticatedAdminPromoCodesRouteImport } from './routes/_authenticated/admin/promo-codes'
import { Route as AuthenticatedAdminTransactionsRouteImport } from './routes/_authenticated/admin/transactions'
import { Route as AuthenticatedApplicationsApplicationIdRouteImport } from './routes/_authenticated/applications.$applicationId'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated/campaigns.index'
import { Route as AuthenticatedCampaignsCampaignIdRouteImport } from './routes/_authenticated/campaigns.$campaignId'
import { Route as AuthenticatedCampaignsNewRouteImport } from './routes/_authenticated/campaigns.new'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth/google'
import { Route as ApiAuthLinkedinRouteImport } from './routes/api/auth/linkedin'
import { Route as ApiCampaignsCampaignIdRouteImport } from './routes/api/campaigns.$campaignId'
import { Route as ApiCatalogsUniversitiesRouteImport } from './routes/api/catalogs/universities'
import { Route as ApiPaymentInitiateRouteImport } from './routes/api/payment/initiate'
import { Route as ApiPaymentWebhookRouteImport } from './routes/api/payment/webhook'
import { Route as ApiPromoBypassRouteImport } from './routes/api/promo/bypass'
import { Route as ApiPromoValidateRouteImport } from './routes/api/promo/validate'
import { Route as ApiPublicJobsRouteImport } from './routes/api/public/jobs'
import { Route as AuthenticatedCampaignsCampaignIdIndexRouteImport } from './routes/_authenticated/campaigns.$campaignId.index'
import { Route as AuthenticatedCampaignsCampaignIdExtendRouteImport } from './routes/_authenticated/campaigns.$campaignId.extend'
import { Route as AuthenticatedCampaignsCampaignIdPayRouteImport } from './routes/_authenticated/campaigns.$campaignId.pay'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth/google.callback'
import { Route as ApiAuthLinkedinCallbackRouteImport } from './routes/api/auth/linkedin.callback'
import { Route as ApiPaymentChargeStatusChargeIdRouteImport } from './routes/api/payment/charge-status.$chargeId'
import { Route as ApiPaymentStatusTxRefRouteImport } from './routes/api/payment/status.$txRef'
import { Route as ApiPaymentStatusCampaignCampaignIdRouteImport } from './routes/api/payment/status/campaign.$campaignId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCandidatesRoute = AuthenticatedCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactCenterRoute =
  AuthenticatedContactCenterRouteImport.update({
    id: '/contact-center',
    path: '/contact-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKanbanRoute = AuthenticatedKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPlansRoute = ApiPlansRouteImport.update({
  id: '/api/plans',
  path: '/api/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyCampaignIdRoute = ApplyCampaignIdRouteImport.update({
  id: '/apply/$campaignId',
  path: '/apply/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment/failed',
  path: '/payment/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionCallbackRoute = SessionCallbackRouteImport.update({
  id: '/session/callback',
  path: '/session/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSignoutRoute = SessionSignoutRouteImport.update({
  id: '/session/signout',
  path: '/session/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const SharePublicTokenRoute = SharePublicTokenRouteImport.update({
  id: '/share/$publicToken',
  path: '/share/$publicToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPromoCodesRoute =
  AuthenticatedAdminPromoCodesRouteImport.update({
    id: '/promo-codes',
    path: '/promo-codes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTransactionsRoute =
  AuthenticatedAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedApplicationsApplicationIdRoute =
  AuthenticatedApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdRoute =
  AuthenticatedCampaignsCampaignIdRouteImport.update({
    id: '/campaigns/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignsNewRoute =
  AuthenticatedCampaignsNewRouteImport.update({
    id: '/campaigns/new',
    path: '/campaigns/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLinkedinRoute = ApiAuthLinkedinRouteImport.update({
  id: '/api/auth/linkedin',
  path: '/api/auth/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCampaignsCampaignIdRoute = ApiCampaignsCampaignIdRouteImport.update({
  id: '/api/campaigns/$campaignId',
  path: '/api/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCatalogsUniversitiesRoute = ApiCatalogsUniversitiesRouteImport.update({
  id: '/api/catalogs/universities',
  path: '/api/catalogs/universities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentInitiateRoute = ApiPaymentInitiateRouteImport.update({
  id: '/api/payment/initiate',
  path: '/api/payment/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookRoute = ApiPaymentWebhookRouteImport.update({
  id: '/api/payment/webhook',
  path: '/api/payment/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromoBypassRoute = ApiPromoBypassRouteImport.update({
  id: '/api/promo/bypass',
  path: '/api/promo/bypass',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPromoValidateRoute = ApiPromoValidateRouteImport.update({
  id: '/api/promo/validate',
  path: '/api/promo/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJobsRoute = ApiPublicJobsRouteImport.update({
  id: '/api/public/jobs',
  path: '/api/public/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCampaignsCampaignIdIndexRoute =
  AuthenticatedCampaignsCampaignIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdExtendRoute =
  AuthenticatedCampaignsCampaignIdExtendRouteImport.update({
    id: '/extend',
    path: '/extend',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const AuthenticatedCampaignsCampaignIdPayRoute =
  AuthenticatedCampaignsCampaignIdPayRouteImport.update({
    id: '/pay',
    path: '/pay',
    getParentRoute: () => AuthenticatedCampaignsCampaignIdRoute,
  } as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)
const ApiAuthLinkedinCallbackRoute = ApiAuthLinkedinCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthLinkedinRoute,
} as any)
const ApiPaymentChargeStatusChargeIdRoute =
  ApiPaymentChargeStatusChargeIdRouteImport.update({
    id: '/api/payment/charge-status/$chargeId',
    path: '/api/payment/charge-status/$chargeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentStatusTxRefRoute = ApiPaymentStatusTxRefRouteImport.update({
  id: '/api/payment/status/$txRef',
  path: '/api/payment/status/$txRef',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentStatusCampaignCampaignIdRoute =
  ApiPaymentStatusCampaignCampaignIdRouteImport.update({
    id: '/api/payment/status/campaign/$campaignId',
    path: '/api/payment/status/campaign/$campaignId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jobs': typeof JobsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/candidates': typeof AuthenticatedCandidatesRoute
  '/contact-center': typeof AuthenticatedContactCenterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/api/plans': typeof ApiPlansRoute
  '/apply/$campaignId': typeof ApplyCampaignIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/session/callback': typeof SessionCallbackRoute
  '/session/signout': typeof SessionSignoutRoute
  '/share/$publicToken': typeof SharePublicTokenRoute
  '/admin/promo-codes': typeof AuthenticatedAdminPromoCodesRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/linkedin': typeof ApiAuthLinkedinRouteWithChildren
  '/api/campaigns/$campaignId': typeof ApiCampaignsCampaignIdRoute
  '/api/catalogs/universities': typeof ApiCatalogsUniversitiesRoute
  '/api/payment/initiate': typeof ApiPaymentInitiateRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/promo/bypass': typeof ApiPromoBypassRoute
  '/api/promo/validate': typeof ApiPromoValidateRoute
  '/api/public/jobs': typeof ApiPublicJobsRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/campaigns/$campaignId/extend': typeof AuthenticatedCampaignsCampaignIdExtendRoute
  '/campaigns/$campaignId/pay': typeof AuthenticatedCampaignsCampaignIdPayRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/linkedin/callback': typeof ApiAuthLinkedinCallbackRoute
  '/api/payment/charge-status/$chargeId': typeof ApiPaymentChargeStatusChargeIdRoute
  '/api/payment/status/$txRef': typeof ApiPaymentStatusTxRefRoute
  '/campaigns/$campaignId/': typeof AuthenticatedCampaignsCampaignIdIndexRoute
  '/api/payment/status/campaign/$campaignId': typeof ApiPaymentStatusCampaignCampaignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jobs': typeof JobsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/candidates': typeof AuthenticatedCandidatesRoute
  '/contact-center': typeof AuthenticatedContactCenterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/kanban': typeof AuthenticatedKanbanRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/api/plans': typeof ApiPlansRoute
  '/apply/$campaignId': typeof ApplyCampaignIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/session/callback': typeof SessionCallbackRoute
  '/session/signout': typeof SessionSignoutRoute
  '/share/$publicToken': typeof SharePublicTokenRoute
  '/admin/promo-codes': typeof AuthenticatedAdminPromoCodesRoute
  '/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/linkedin': typeof ApiAuthLinkedinRouteWithChildren
  '/api/campaigns/$campaignId': typeof ApiCampaignsCampaignIdRoute
  '/api/catalogs/universities': typeof ApiCatalogsUniversitiesRoute
  '/api/payment/initiate': typeof ApiPaymentInitiateRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/promo/bypass': typeof ApiPromoBypassRoute
  '/api/promo/validate': typeof ApiPromoValidateRoute
  '/api/public/jobs': typeof ApiPublicJobsRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/campaigns/$campaignId/extend': typeof AuthenticatedCampaignsCampaignIdExtendRoute
  '/campaigns/$campaignId/pay': typeof AuthenticatedCampaignsCampaignIdPayRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/linkedin/callback': typeof ApiAuthLinkedinCallbackRoute
  '/api/payment/charge-status/$chargeId': typeof ApiPaymentChargeStatusChargeIdRoute
  '/api/payment/status/$txRef': typeof ApiPaymentStatusTxRefRoute
  '/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdIndexRoute
  '/api/payment/status/campaign/$campaignId': typeof ApiPaymentStatusCampaignCampaignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/jobs': typeof JobsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/candidates': typeof AuthenticatedCandidatesRoute
  '/_authenticated/contact-center': typeof AuthenticatedContactCenterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/kanban': typeof AuthenticatedKanbanRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/api/plans': typeof ApiPlansRoute
  '/apply/$campaignId': typeof ApplyCampaignIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/session/callback': typeof SessionCallbackRoute
  '/session/signout': typeof SessionSignoutRoute
  '/share/$publicToken': typeof SharePublicTokenRoute
  '/_authenticated/admin/promo-codes': typeof AuthenticatedAdminPromoCodesRoute
  '/_authenticated/admin/transactions': typeof AuthenticatedAdminTransactionsRoute
  '/_authenticated/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/_authenticated/campaigns/$campaignId': typeof AuthenticatedCampaignsCampaignIdRouteWithChildren
  '/_authenticated/campaigns/new': typeof AuthenticatedCampaignsNewRoute
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/linkedin': typeof ApiAuthLinkedinRouteWithChildren
  '/api/campaigns/$campaignId': typeof ApiCampaignsCampaignIdRoute
  '/api/catalogs/universities': typeof ApiCatalogsUniversitiesRoute
  '/api/payment/initiate': typeof ApiPaymentInitiateRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/api/promo/bypass': typeof ApiPromoBypassRoute
  '/api/promo/validate': typeof ApiPromoValidateRoute
  '/api/public/jobs': typeof ApiPublicJobsRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/campaigns/$campaignId/extend': typeof AuthenticatedCampaignsCampaignIdExtendRoute
  '/_authenticated/campaigns/$campaignId/pay': typeof AuthenticatedCampaignsCampaignIdPayRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
  '/api/auth/linkedin/callback': typeof ApiAuthLinkedinCallbackRoute
  '/api/payment/charge-status/$chargeId': typeof ApiPaymentChargeStatusChargeIdRoute
  '/api/payment/status/$txRef': typeof ApiPaymentStatusTxRefRoute
  '/_authenticated/campaigns/$campaignId/': typeof AuthenticatedCampaignsCampaignIdIndexRoute
  '/api/payment/status/campaign/$campaignId': typeof ApiPaymentStatusCampaignCampaignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/jobs'
    | '/reset-password'
    | '/verify-email'
    | '/admin'
    | '/candidates'
    | '/contact-center'
    | '/dashboard'
    | '/kanban'
    | '/onboarding'
    | '/payments'
    | '/settings'
    | '/support'
    | '/api/plans'
    | '/apply/$campaignId'
    | '/payment/failed'
    | '/payment/success'
    | '/session/callback'
    | '/session/signout'
    | '/share/$publicToken'
    | '/admin/promo-codes'
    | '/admin/transactions'
    | '/applications/$applicationId'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/api/auth/google'
    | '/api/auth/linkedin'
    | '/api/campaigns/$campaignId'
    | '/api/catalogs/universities'
    | '/api/payment/initiate'
    | '/api/payment/webhook'
    | '/api/promo/bypass'
    | '/api/promo/validate'
    | '/api/public/jobs'
    | '/campaigns/'
    | '/campaigns/$campaignId/extend'
    | '/campaigns/$campaignId/pay'
    | '/api/auth/google/callback'
    | '/api/auth/linkedin/callback'
    | '/api/payment/charge-status/$chargeId'
    | '/api/payment/status/$txRef'
    | '/campaigns/$campaignId/'
    | '/api/payment/status/campaign/$campaignId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/jobs'
    | '/reset-password'
    | '/verify-email'
    | '/admin'
    | '/candidates'
    | '/contact-center'
    | '/dashboard'
    | '/kanban'
    | '/onboarding'
    | '/payments'
    | '/settings'
    | '/support'
    | '/api/plans'
    | '/apply/$campaignId'
    | '/payment/failed'
    | '/payment/success'
    | '/session/callback'
    | '/session/signout'
    | '/share/$publicToken'
    | '/admin/promo-codes'
    | '/admin/transactions'
    | '/applications/$applicationId'
    | '/campaigns/new'
    | '/api/auth/google'
    | '/api/auth/linkedin'
    | '/api/campaigns/$campaignId'
    | '/api/catalogs/universities'
    | '/api/payment/initiate'
    | '/api/payment/webhook'
    | '/api/promo/bypass'
    | '/api/promo/validate'
    | '/api/public/jobs'
    | '/campaigns'
    | '/campaigns/$campaignId/extend'
    | '/campaigns/$campaignId/pay'
    | '/api/auth/google/callback'
    | '/api/auth/linkedin/callback'
    | '/api/payment/charge-status/$chargeId'
    | '/api/payment/status/$txRef'
    | '/campaigns/$campaignId'
    | '/api/payment/status/campaign/$campaignId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/jobs'
    | '/reset-password'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/candidates'
    | '/_authenticated/contact-center'
    | '/_authenticated/dashboard'
    | '/_authenticated/kanban'
    | '/_authenticated/onboarding'
    | '/_authenticated/payments'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/api/plans'
    | '/apply/$campaignId'
    | '/payment/failed'
    | '/payment/success'
    | '/session/callback'
    | '/session/signout'
    | '/share/$publicToken'
    | '/_authenticated/admin/promo-codes'
    | '/_authenticated/admin/transactions'
    | '/_authenticated/applications/$applicationId'
    | '/_authenticated/campaigns/$campaignId'
    | '/_authenticated/campaigns/new'
    | '/api/auth/google'
    | '/api/auth/linkedin'
    | '/api/campaigns/$campaignId'
    | '/api/catalogs/universities'
    | '/api/payment/initiate'
    | '/api/payment/webhook'
    | '/api/promo/bypass'
    | '/api/promo/validate'
    | '/api/public/jobs'
    | '/_authenticated/campaigns/'
    | '/_authenticated/campaigns/$campaignId/extend'
    | '/_authenticated/campaigns/$campaignId/pay'
    | '/api/auth/google/callback'
    | '/api/auth/linkedin/callback'
    | '/api/payment/charge-status/$chargeId'
    | '/api/payment/status/$txRef'
    | '/_authenticated/campaigns/$campaignId/'
    | '/api/payment/status/campaign/$campaignId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  JobsRoute: typeof JobsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ApiPlansRoute: typeof ApiPlansRoute
  ApplyCampaignIdRoute: typeof ApplyCampaignIdRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  SessionCallbackRoute: typeof SessionCallbackRoute
  SessionSignoutRoute: typeof SessionSignoutRoute
  SharePublicTokenRoute: typeof SharePublicTokenRoute
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiAuthLinkedinRoute: typeof ApiAuthLinkedinRouteWithChildren
  ApiCampaignsCampaignIdRoute: typeof ApiCampaignsCampaignIdRoute
  ApiCatalogsUniversitiesRoute: typeof ApiCatalogsUniversitiesRoute
  ApiPaymentInitiateRoute: typeof ApiPaymentInitiateRoute
  ApiPaymentWebhookRoute: typeof ApiPaymentWebhookRoute
  ApiPromoBypassRoute: typeof ApiPromoBypassRoute
  ApiPromoValidateRoute: typeof ApiPromoValidateRoute
  ApiPublicJobsRoute: typeof ApiPublicJobsRoute
  ApiPaymentChargeStatusChargeIdRoute: typeof ApiPaymentChargeStatusChargeIdRoute
  ApiPaymentStatusTxRefRoute: typeof ApiPaymentStatusTxRefRoute
  ApiPaymentStatusCampaignCampaignIdRoute: typeof ApiPaymentStatusCampaignCampaignIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/candidates': {
      id: '/_authenticated/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AuthenticatedCandidatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contact-center': {
      id: '/_authenticated/contact-center'
      path: '/contact-center'
      fullPath: '/contact-center'
      preLoaderRoute: typeof AuthenticatedContactCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kanban': {
      id: '/_authenticated/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AuthenticatedKanbanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/plans': {
      id: '/api/plans'
      path: '/api/plans'
      fullPath: '/api/plans'
      preLoaderRoute: typeof ApiPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$campaignId': {
      id: '/apply/$campaignId'
      path: '/apply/$campaignId'
      fullPath: '/apply/$campaignId'
      preLoaderRoute: typeof ApplyCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/callback': {
      id: '/session/callback'
      path: '/session/callback'
      fullPath: '/session/callback'
      preLoaderRoute: typeof SessionCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/signout': {
      id: '/session/signout'
      path: '/session/signout'
      fullPath: '/session/signout'
      preLoaderRoute: typeof SessionSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$publicToken': {
      id: '/share/$publicToken'
      path: '/share/$publicToken'
      fullPath: '/share/$publicToken'
      preLoaderRoute: typeof SharePublicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/promo-codes': {
      id: '/_authenticated/admin/promo-codes'
      path: '/promo-codes'
      fullPath: '/admin/promo-codes'
      preLoaderRoute: typeof AuthenticatedAdminPromoCodesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/transactions': {
      id: '/_authenticated/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AuthenticatedAdminTransactionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/applications/$applicationId': {
      id: '/_authenticated/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/$campaignId': {
      id: '/_authenticated/campaigns/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns/new': {
      id: '/_authenticated/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AuthenticatedCampaignsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/linkedin': {
      id: '/api/auth/linkedin'
      path: '/api/auth/linkedin'
      fullPath: '/api/auth/linkedin'
      preLoaderRoute: typeof ApiAuthLinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/campaigns/$campaignId': {
      id: '/api/campaigns/$campaignId'
      path: '/api/campaigns/$campaignId'
      fullPath: '/api/campaigns/$campaignId'
      preLoaderRoute: typeof ApiCampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/catalogs/universities': {
      id: '/api/catalogs/universities'
      path: '/api/catalogs/universities'
      fullPath: '/api/catalogs/universities'
      preLoaderRoute: typeof ApiCatalogsUniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/initiate': {
      id: '/api/payment/initiate'
      path: '/api/payment/initiate'
      fullPath: '/api/payment/initiate'
      preLoaderRoute: typeof ApiPaymentInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook': {
      id: '/api/payment/webhook'
      path: '/api/payment/webhook'
      fullPath: '/api/payment/webhook'
      preLoaderRoute: typeof ApiPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promo/bypass': {
      id: '/api/promo/bypass'
      path: '/api/promo/bypass'
      fullPath: '/api/promo/bypass'
      preLoaderRoute: typeof ApiPromoBypassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/promo/validate': {
      id: '/api/promo/validate'
      path: '/api/promo/validate'
      fullPath: '/api/promo/validate'
      preLoaderRoute: typeof ApiPromoValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jobs': {
      id: '/api/public/jobs'
      path: '/api/public/jobs'
      fullPath: '/api/public/jobs'
      preLoaderRoute: typeof ApiPublicJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/campaigns/$campaignId/': {
      id: '/_authenticated/campaigns/$campaignId/'
      path: '/'
      fullPath: '/campaigns/$campaignId/'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdIndexRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/extend': {
      id: '/_authenticated/campaigns/$campaignId/extend'
      path: '/extend'
      fullPath: '/campaigns/$campaignId/extend'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdExtendRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/_authenticated/campaigns/$campaignId/pay': {
      id: '/_authenticated/campaigns/$campaignId/pay'
      path: '/pay'
      fullPath: '/campaigns/$campaignId/pay'
      preLoaderRoute: typeof AuthenticatedCampaignsCampaignIdPayRouteImport
      parentRoute: typeof AuthenticatedCampaignsCampaignIdRoute
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
    '/api/auth/linkedin/callback': {
      id: '/api/auth/linkedin/callback'
      path: '/callback'
      fullPath: '/api/auth/linkedin/callback'
      preLoaderRoute: typeof ApiAuthLinkedinCallbackRouteImport
      parentRoute: typeof ApiAuthLinkedinRoute
    }
    '/api/payment/charge-status/$chargeId': {
      id: '/api/payment/charge-status/$chargeId'
      path: '/api/payment/charge-status/$chargeId'
      fullPath: '/api/payment/charge-status/$chargeId'
      preLoaderRoute: typeof ApiPaymentChargeStatusChargeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/status/$txRef': {
      id: '/api/payment/status/$txRef'
      path: '/api/payment/status/$txRef'
      fullPath: '/api/payment/status/$txRef'
      preLoaderRoute: typeof ApiPaymentStatusTxRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/status/campaign/$campaignId': {
      id: '/api/payment/status/campaign/$campaignId'
      path: '/api/payment/status/campaign/$campaignId'
      fullPath: '/api/payment/status/campaign/$campaignId'
      preLoaderRoute: typeof ApiPaymentStatusCampaignCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminPromoCodesRoute: typeof AuthenticatedAdminPromoCodesRoute
  AuthenticatedAdminTransactionsRoute: typeof AuthenticatedAdminTransactionsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminPromoCodesRoute: AuthenticatedAdminPromoCodesRoute,
  AuthenticatedAdminTransactionsRoute: AuthenticatedAdminTransactionsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCampaignsCampaignIdRouteChildren {
  AuthenticatedCampaignsCampaignIdExtendRoute: typeof AuthenticatedCampaignsCampaignIdExtendRoute
  AuthenticatedCampaignsCampaignIdPayRoute: typeof AuthenticatedCampaignsCampaignIdPayRoute
  AuthenticatedCampaignsCampaignIdIndexRoute: typeof AuthenticatedCampaignsCampaignIdIndexRoute
}

const AuthenticatedCampaignsCampaignIdRouteChildren: AuthenticatedCampaignsCampaignIdRouteChildren =
  {
    AuthenticatedCampaignsCampaignIdExtendRoute:
      AuthenticatedCampaignsCampaignIdExtendRoute,
    AuthenticatedCampaignsCampaignIdPayRoute:
      AuthenticatedCampaignsCampaignIdPayRoute,
    AuthenticatedCampaignsCampaignIdIndexRoute:
      AuthenticatedCampaignsCampaignIdIndexRoute,
  }

const AuthenticatedCampaignsCampaignIdRouteWithChildren =
  AuthenticatedCampaignsCampaignIdRoute._addFileChildren(
    AuthenticatedCampaignsCampaignIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCandidatesRoute: typeof AuthenticatedCandidatesRoute
  AuthenticatedContactCenterRoute: typeof AuthenticatedContactCenterRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKanbanRoute: typeof AuthenticatedKanbanRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedApplicationsApplicationIdRoute: typeof AuthenticatedApplicationsApplicationIdRoute
  AuthenticatedCampaignsCampaignIdRoute: typeof AuthenticatedCampaignsCampaignIdRouteWithChildren
  AuthenticatedCampaignsNewRoute: typeof AuthenticatedCampaignsNewRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCandidatesRoute: AuthenticatedCandidatesRoute,
  AuthenticatedContactCenterRoute: AuthenticatedContactCenterRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKanbanRoute: AuthenticatedKanbanRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedApplicationsApplicationIdRoute:
    AuthenticatedApplicationsApplicationIdRoute,
  AuthenticatedCampaignsCampaignIdRoute:
    AuthenticatedCampaignsCampaignIdRouteWithChildren,
  AuthenticatedCampaignsNewRoute: AuthenticatedCampaignsNewRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

interface ApiAuthLinkedinRouteChildren {
  ApiAuthLinkedinCallbackRoute: typeof ApiAuthLinkedinCallbackRoute
}

const ApiAuthLinkedinRouteChildren: ApiAuthLinkedinRouteChildren = {
  ApiAuthLinkedinCallbackRoute: ApiAuthLinkedinCallbackRoute,
}

const ApiAuthLinkedinRouteWithChildren = ApiAuthLinkedinRoute._addFileChildren(
  ApiAuthLinkedinRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  JobsRoute: JobsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ApiPlansRoute: ApiPlansRoute,
  ApplyCampaignIdRoute: ApplyCampaignIdRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  SessionCallbackRoute: SessionCallbackRoute,
  SessionSignoutRoute: SessionSignoutRoute,
  SharePublicTokenRoute: SharePublicTokenRoute,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiAuthLinkedinRoute: ApiAuthLinkedinRouteWithChildren,
  ApiCampaignsCampaignIdRoute: ApiCampaignsCampaignIdRoute,
  ApiCatalogsUniversitiesRoute: ApiCatalogsUniversitiesRoute,
  ApiPaymentInitiateRoute: ApiPaymentInitiateRoute,
  ApiPaymentWebhookRoute: ApiPaymentWebhookRoute,
  ApiPromoBypassRoute: ApiPromoBypassRoute,
  ApiPromoValidateRoute: ApiPromoValidateRoute,
  ApiPublicJobsRoute: ApiPublicJobsRoute,
  ApiPaymentChargeStatusChargeIdRoute: ApiPaymentChargeStatusChargeIdRoute,
  ApiPaymentStatusTxRefRoute: ApiPaymentStatusTxRefRoute,
  ApiPaymentStatusCampaignCampaignIdRoute:
    ApiPaymentStatusCampaignCampaignIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
